<?php
  $this->headTitle($this->translate('manager.job.details'));
  $statusMap = $this->job->getStatusMap();
?>

<div class="sidebar-page manager-manager-details">
  <div class="box">
    <label><?php echo $this->escapeHtml($this->translate('manager.job.details')) ?></label>
    <ul class="details">
      <li><label><?php echo $this->escapeHtml($this->translate('manager.job.id')) ?>:</label><?php echo $job->id ?></li>
      <li><label><?php echo $this->escapeHtml($this->translate('manager.job.creationDate')) ?>:</label><?php echo date('Y/m/d H:i:s', $job->creationDate) ?></li>
      <li><label><?php echo $this->escapeHtml($this->translate('manager.job.status')) ?>:</label><?php echo $this->escapeHtml($statusMap[$job->status]) ?></li>
      <li>
        <label><?php echo $this->escapeHtml($this->translate('manager.job.documents')) ?>:</label>
        <ul id="documents" class="details">
          <?php foreach($this->job->documents as $document) : ?>
            <li><a href="<?php echo $this->url('manager', array('action' => 'download', 'id' => $document->id)) . '" title="' . $this->translate('application.generic.download') ?>"><?php echo $document->getFileName(); ?></a></li>
          <?php endforeach ?>
        </ul>
      </li>
    </ul>
  </div>
</div>

<aside>
  <h4><?php echo $this->escapeHtml($this->translate('manager.job.details.document.list')) ?></h4>
  <ul>
    <li><?php echo $this->escapeHtml($this->translate('manager.job.details.document.docx')) ?></li>
    <li><?php echo $this->escapeHtml($this->translate('manager.job.details.document.nlmxml')) ?></li>
    <li><?php echo $this->escapeHtml($this->translate('manager.job.details.document.bib.xml')) ?></li>
    <li><?php echo $this->escapeHtml($this->translate('manager.job.details.document.bib.tex')) ?></li>
    <li><?php echo $this->escapeHtml($this->translate('manager.job.details.document.html')) ?></li>
    <li><?php echo $this->escapeHtml($this->translate('manager.job.details.document.pdf')) ?></li>
    <li><?php echo $this->escapeHtml($this->translate('manager.job.details.document.zip')) ?></li>
  </ul>
</aside>
