<?php
use Manager\Entity\Job;
$this->headTitle($this->translate('manager.job.list'));
$user = $this->identity();
?>

<div class="page manager-manager-list">
  <?php
  if ($this->jobs) {
    echo '<table class="table footable"><thead><tr>';
    echo '<th class="id" data-toggle="true">' . $this->translate('manager.job.id') . '</th>';
    if ($user->isAdministrator()) {
      echo '<th class="user" data-hide="phone">' . $this->translate('manager.job.user') . '</th>';
    }
    echo '<th class="id">' . $this->translate('manager.job.status') . '</th>';
    echo '<th class="creation-date" data-hide="phone">' . $this->translate('manager.job.creationDate') . '</th>';
    echo '<th class="upload" data-hide="phone">' . $this->translate('manager.job.uploadFileName') . '</th>';
    echo '<th class="actions" data-hide="phone">' . $this->translate('application.generic.actions') . '</th>';
    echo '</tr></thead><tbody>';

    foreach ($this->jobs as $job) {
      if (!isset($statusMap)) $statusMap = $job->getStatusMap();

      $document = $job->getStageDocument(JOB_CONVERSION_STAGE_UNCONVERTED);
      $uploadFileName = $document ? basename($document->path) : '';

      echo '<tr>';
      echo '<td>' . $this->escapeHtml($job->id) . '</td>';
      if ($user->isAdministrator()) {
        echo '<td>' . $this->escapeHtml($job->user->email) . '</td>';
      }
      echo '<td>' . $this->escapeHtml($statusMap[$job->status]) . '</td>';
      echo '<td>' . date('Y/m/d H:i:s', $job->creationDate) . '</td>';
      echo '<td>' . $this->escapeHtml($uploadFileName) . '</td>';
      echo '<td>';
      if ($job->status == JOB_STATUS_COMPLETED) {
        echo '<a href="' . $this->url('manager', array('action' => 'details', 'id' => $job->id)) . '" title="' . $this->translate('application.generic.details') . '" class="action details-action"></a>';
      }
      echo '</td>';
      echo '</tr>';
    }

    echo '</tbody></table>';

    echo $this->paginationControl(
      $this->jobs,
      'sliding',
      array('partial/paginator.phtml', 'Application'),
      array('route/manager_list')
    );
  }
  ?>
</div>
