#!/bin/sh
cd $OPENSHIFT_REPO_DIR
echo "Executing OpenShift deploy hook"

cp config/autoload/openshift.php.dist config/autoload/local.php

COMPOSER_HOME='~/app-root/data/.composer'
./composer.phar self-update
./composer.phar install

vendor/bin/doctrine-module  orm:schema-tool:update --force
