<?php
if (isset($this->loginForm)) {
  $loginForm->setAttribute('action', $this->url('user', array('action' => 'login')));
  $loginForm = $this->loginForm;
  $loginForm->prepare();
  $loginForm = $this->form()->render($loginForm);
}

if (isset($this->registrationForm)) {
  $registrationForm->setAttribute('action', $this->url('user', array('action' => 'register')));
  $registrationForm = $this->registrationForm;
  $registrationForm->prepare();
  $registrationForm = $this->form()->render($registrationForm);
}

if (isset($this->uploadForm)) {
  $uploadForm->setAttribute('action', $this->url('manager', array('action' => 'upload')));
  $uploadForm = $this->uploadForm;
  $uploadForm->prepare();
  $uploadForm = $this->form()->render($uploadForm);
}
?>
<div class="sidebar-page user-user-index">
  <?php if (!$user = $this->identity()) : ?>
    <div class="box-wrapper">
      <div class="box">
        <label><?php echo $this->translate('user.loginForm.login') ?></label>
        <?php echo $loginForm; ?>
      </div>

      <div class="box">
        <label><?php echo $this->translate('user.registrationForm.register') ?></label>
        <?php echo $registrationForm; ?>
      </div>
    </div>
  <?php endif ?>

  <?php if ($this->uploadForm) : ?>
    <div class="box-wrapper">
      <div class="box">
        <label><?php echo $this->translate('manager.uploadForm.uploadDocument') ?></label>
        <?php echo $uploadForm; ?>
      </div>
    </div>
  <?php endif ?>

</div>
<?php echo $this->partial('_sideBar.phtml'); ?>
