<?php
if (isset($this->loginForm)) {
  $loginForm->setAttribute('action', $this->url('user', array('action' => 'login')));
  $loginForm = $this->loginForm;
  $loginForm->prepare();
  $loginForm = $this->form()->render($loginForm);
}

if (isset($this->registrationForm)) {
  $registrationForm->setAttribute('action', $this->url('user', array('action' => 'register')));
  $registrationForm = $this->registrationForm;
  $registrationForm->prepare();
  $registrationForm = $this->form()->render($registrationForm);
}
?>
<div class="sidebar-page user-user-index">
  <?php if (!$user = $this->identity()) : ?>
    <div class="authenticate">
      <div class="box-container first">
        <div class="box">
          <label><?php echo $this->translate('user.loginForm.login') ?></label>
          <?php echo $loginForm; ?>
        </div>
     </div>

      <div class="box-container">
        <div class="box">
          <label><?php echo $this->translate('user.registrationForm.register') ?></label>
          <?php echo $registrationForm; ?>
        </div>
      </div>
    </div>
  <?php endif ?>

</div>
<?php echo $this->partial('_sideBar.phtml'); ?>
