<?php
if (isset($this->loginForm)) {
  $loginForm = $this->loginForm;
  $loginForm->prepare();
  $loginForm = $this->form()->render($loginForm);
}
?>
<div class="front-page">
  <?php if (isset($loginForm)) : ?>
    <div class="box">
      <label><?php echo $this->translate('user.loginForm.login') ?></label>
      <?php echo $loginForm; ?>
    </div>
  <?php endif ?>
</div>
<?php echo $this->partial('_sideBar.phtml'); ?>
