#!/bin/sh
# description: Start or stop the xmlps queues
#
### BEGIN INIT INFO
# Provides: xmlps queues
# Default-Start: 2 3 5
# Default-Stop: 0 1 6
# Description: Start or stop the xml parsing server queues
### END INIT INFO
name='XMLPSQueues'
su='su www-data -c'
base_path='/var/www'

case "$1" in
'start')
    cd $base_path
    $su 'php public/index.php queue doctrine docx --start' &
    echo "Started DocX queue [PID $!]"
    $su 'php public/index.php queue doctrine nlmxml --start' &
    echo "Started NLMXML queue [PID $!]"
    $su 'php public/index.php queue doctrine references --start' &
    echo "Started References queue [PID $!]"
    $su 'php public/index.php queue doctrine bibtex --start' &
    echo "Started Bibtex queue [PID $!]"
    $su 'php public/index.php queue doctrine bibtexreferences --start' &
    echo "Started BibtexReferences queue [PID $!]"
    $su 'php public/index.php queue doctrine html --start' &
    echo "Started HTML queue [PID $!]"
    $su 'php public/index.php queue doctrine citationstyle --start' &
    echo "Started CitationStyle queue [PID $!]"
    $su 'php public/index.php queue doctrine pdf --start' &
    echo "Started PDF pdf queue [PID $!]"
    $su 'php public/index.php queue doctrine xmp --start' &
    echo "Started XMP queue [PID $!]"
    $su 'php public/index.php queue doctrine zip --start' &
    echo "Started Zip queue [PID $!]"
    ;;
'stop')
    RUNNING=`ps ax | grep 'public/index.php queue doctrine' | grep -v grep | awk '{print $1}'`
    for pid in $RUNNING; do
        echo "Killing queue process [PID $pid]"
        $su "kill -9 $pid"
    done
    ;;
'restart')
    $0 stop ; $0 start
    ;;
*)
    echo "Usage: $0 { start | stop | restart }"
    ;;
esac
exit 1

