<?php $this->headTitle($this->translate('application.layout.systemLog.list')); ?>

<div class="page system-log-page">
  <?php
  if ($this->logEntries) {
    echo '<table class="table table-system-log footable"><thead><tr>';
    echo '<th class="time" data-toggle="true">' . $this->translate('admin.log.time') . '</th>';
    echo '<th class="ip-address" data-hide="phone">' . $this->translate('admin.log.ipAddress') . '</th>';
    echo '<th class="priority" data-hide="phone">' . $this->translate('admin.log.priority') . '</th>';
    echo '<th class="message">' . $this->translate('admin.log.message') . '</th>';
    echo '</tr></thead><tbody>';

    foreach ($this->logEntries as $logEntry) {
      echo '<tr>';
      echo '<td>' . $this->dateFormat($logEntry->timestamp, IntlDateFormatter::SHORT, IntlDateFormatter::SHORT, 'en_Us') . '</td>';
      echo '<td>' . $this->escapeHtml($logEntry->ip) . '</td>';
      echo '<td>' . $this->escapeHtml($this->priorities[$logEntry->priority]) . '</td>';
      echo '<td>' . $this->escapeHtml($logEntry->message) . '</td>';
      echo '</tr>';
    }

    echo '</tbody></table>';

    echo $this->paginationControl(
      $this->logEntries,
      'sliding',
      array('partial/paginator.phtml', 'Application'),
      array('route' => 'admin/system-log')
    );
  }

  ?>
</div>
