<html>
<head>
  <meta charset="UTF-8">
  <meta name="documentUrl" content="/manager/xml/id/<?php echo $jobId ?>">
</head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
  <script type="text/javascript" src="/scientist/app.js"></script>
  <script type="text/javascript">

    window.onload = function() {
      // DocumentPage loads the provided document url
      var documentUrl = document.querySelector('meta[name=documentUrl').getAttribute('content');

      window.app = DocumentPage.static.mount({
        documentUrl: documentUrl,
        onSave: function(xml) {

            var params = {'content':xml};
            $.post(documentUrl, params, function(data) 
            {
                // post processing code goes here
            }, 'json');

        }
      }, document.body);
    };
  </script>
  <link href='/scientist/app.css' rel='stylesheet' type='text/css'/>
<body>

</body>
</html>
