<?php
$this->headTitle($this->translate('admin.userManagement.removeUser'));

if (isset($this->userRemovalForm)) {
  $userRemovalForm->setAttribute('action', $this->url('admin/user_management', array('action' => 'remove')));
  $userRemovalForm = $this->userRemovalForm;
  $userRemovalForm->prepare();
  $userRemovalForm = $this->form()->render($userRemovalForm);
}

?>
<div class="page">
  <div class="box dialog">
    <label><?php echo $this->translate('application.generic.confirm') ?></label>
    <p class="description"><?php echo $this->escapeHtml(sprintf($this->translate('admin.userManagement.userRemovalConfirm'), $user->email)) ?></p>
    <?php echo $userRemovalForm; ?>
  </div>
</div>
