<div class="front-page">
  <div>Add content here</div>
  <aside>
    <h4><?php echo $this->translate('application.generic.siteTitle'); ?></h4>

    <p><?php echo $this->translate('application.index.sidebarDescription'); ?></p>

    <em><?php echo $this->translate('application.index.sidebarTips'); ?></em>

    <ul>
      <li><?php echo $this->translate('application.index.sidebarTipsPDF'); ?></li>
      <li><?php echo $this->translate('application.index.sidebarTipsCitation'); ?></li>
      <li><?php echo $this->translate('application.index.sidebarTipsCitationReference'); ?></li>
      <li><?php echo $this->translate('application.index.sidebarTipsBibliography'); ?></li>
    </ul>
  </aside>
</div>
