<div class="front-page">
  <div>Left column stuff</div>
  <aside>
    <h4>PKP XML Parsing Service</h4>

    <p>This is a new, experimental service being developed by the Public Knowledge Project to provide unsupervised conversion of Word/compatible inputs to production-ready NLM3 XML, HTML, and PDF. This service is currently under active development and output will not be perfect. Contact axfelix@gmail.com with any questions, and watch this space over the coming months.</p>

    <em>Tips on preparing your document:</em>

    <ul>
      <li>PDFs must have embedded text (i.e. created from an already-digital document). Scanned PDFs must have been OCRed before being uploaded to our service (want us to add OCR support? ask!)</li>
      <li>Ideally, citations (in your document that point to your bibliography) are formatted as numbers in brackets, e.g. [10] or [11,12,13]. Consequently, bracketed numbers should not occur in your document for any other reason.</li>
      <li>Citations can also be formatted as single references in parentheses, e.g. (Clancy, 2010) . Our software will re-style these citations according to the citation style you have selected.</li>
      <li>Any bibliography entries which are not cited in your document are reported in a warning section at the bottom.</li>
    </ul>
  </aside>
</div>
